HeatmapDataWriterService:
  Db:
    LogsConnectionString:
      settings-key: HeatmapDataWriterService-LogsConnString
      types:
      - AzureTableStorage

DwhServiceClient:
  ServiceUrl:
    settings-key: DwhServiceUrl

CryptoIndexServiceClient:
  Instances:
    settings-key: CryptoIndexService-Instances
    types:
    - JsonArray

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
  


  